### ISSUE TITLE
Redmatic Homekit node "universal" --> properties

### ISSUE THREAD

**Issue by FSTNDonald** [rdmtc/RedMatic#471]
Aufgabe:
Die "Regenmenge gestern" einer Homematic Wetterstation (HMIP-SWO) in der iOS Home App darzustellen als Sensor mit numerischem Wert 'xx mm'.

Lösung:
1. zunächst in der CCU3 eine Sysvar erzeugen und im Rain-Counter Script befüllen, funktioniert.
2. Im Node-Red Flow-Designer eine CCU Sysvar Node reinziehen und die erzeugte Sysvar zuweisen, funktioniert - der richtige Wert wird nach deploy auch angezeigt, hier 1,2 mm zum Beispiel.

Problem:
Im Pool der 'homekit nodes' gibt es keinen 'passenden' Node "Regenmenge eines Tages". Also Versuch mit "Universal" Node reinziehen, dort auf Eigenschaften.
Es erscheint eine Auswahlliste verschiedenster Aktor / Sensor Typen, von "AccessoryInformation" bis "WindowClosed" (auch hier kein Precipitation oder Niederschlag leider).
Einige Einträge erzeugen nur eine Fehlermeldung in der Home-App "this accessory ist not currently supported by the home app", andere funktionieren, zeigen aber nicht den richtigen Wert an, sondern 0,0 

Gibt es eine Lösung ?

VG DP

**Comment by djiwondee** [comment]
Hallo @FSTNDonald ,

Homekit kennt aktuell keine [kompatiblen Devices](https://www.apple.com/ios/home/accessories/) für Regenmesser. Für Wetterdaten gibt es nur Temperatur, AirQuality, Luftfeuchtigkeit, CO, CO2, jedoch nicht einmal Luftdruck. 

Siehe: https://developer.apple.com/de/support/homekit-accessory-protocol/
> **Can I create an accessory that isn’t yet supported through an Apple-defined HomeKit service?** 
Yes, you can create an accessory that implements HAP using custom characteristics. In order to control this accessory, you will need to develop a custom app that uses HomeKit APIs. You will not be able to control it through the Home app or Siri.

Somit wird es auch für die Homekit Nodes von Redmatic im Moment keine solche passenden Nodes geben.

Homekit kompatible Lösungen mit mehr (Wetter-)daten nutzen sog. Custom Characteristics des Homekit Accessory Protokolls, um sie in den zugehörigen Apps anzeigen. (z. B. [Stromverbrauch bei EVE Energy](https://www.evehome.com/de/eve-energy))

Du musst Dir also als Workaround erst mal anders behelfen. Ich habe z. B. einen Regensensor für meine Terrasse mit dem "Leak Sensor"-Service abgebildet. Der kennt dann halt auch nur zwei Zustände (`Regen`, `Kein Regen`). Das ist aber schon mal eine Lösung für Automationen, wie z. B. "Fenster schließen" oder "Markise einfahren".

**Comment by FSTNDonald** [comment]
Vielen Dank @djiwondee,
besonders für den Link mit den Homekit kompatiblen Devices - das sieht ja alles sehr 'hard-coded' aus leider, den Link kannte ich nicht.

Ich habe mir bereits für Sonnenschein (Helligkeit) in der CCU einen Schalter erzeugt, der abhängig vom gewünschten Pegel die Stellungen ein/aus annimmt. Der lässt sich per Node-Red in Homekit 'transportieren' und dort kann ich dann per Homekit Automation einen Rolladen zu einem definierten Prozentsatz schliessen.

Für die "Regenmenge von gestern" wollte ich diesen Umweg vermeiden, d.h. Menge gestern <5 mm --> heute Bewässerung einschalten als native Homekit Automation ... nun wirds dann doch wie Sonnenschein sein.

Ich habe Homekit an der Spitze der Pyramide, darunten verschiedene Bridges für ihre jeweiligen Aktoren / Sensoren.  Ob Node-Red oder Homematic oder Aquara oder Homebridge usw., in jeder dieser Meta-Ebenen gibt es scriptbare Automationen für Gott und die Welt, aber sobald man übergreifende Logiken benötigt, hört der Spass leider auf.

Frage ist CLOSED damit, danke.

**Comment by djiwondee** [comment]
Hallo @FSTNDonald 

da haben wir wohl die selben Ideen. 
_Sonne_ ist bei mir ein Bewegungsmelder:
<img width="725" alt="image" src="https://user-images.githubusercontent.com/37173958/104596371-31679880-5674-11eb-97c6-b832ddc40958.png">
_Regen_ ein Lecksensor:
<img width="521" alt="image" src="https://user-images.githubusercontent.com/37173958/104596475-4f34fd80-5674-11eb-9456-15655a085e92.png">

...und ja, auch ich habe ein Mesh-von Systemen und Layern. Das ist halt eine Spielwiese, wo man Zeit und Muse aufbringen muss:
<img width="875" alt="image" src="https://user-images.githubusercontent.com/37173958/104596796-c1a5dd80-5674-11eb-8b64-dcdb8a9bf600.png">
Da bin ich auch immer wieder am Optimieren.

**Comment by FSTNDonald** [comment]
hihi - auch eine nette "Interpretation" ;-))

Ernsthaft - keiner der 3 Protagonisten (A, G, MS) produziert geignete HW, also sollte ich (A) einen umfassenden Standard setzen, an den sich die HW Hersteller halten, um Business zu machen.
Klein-Klein, den HW Herstellern hinterherlaufen, wird das nicht funktionieren.

INTEL hat das mehr als exemplarisch vorgemacht - X86, Flash, PCI, USB, ATX Formfaktor - alles Industriestandards. Wenig selber produziert, technische Eleganz spielt keine Rolle, aber 'Intel Inside' drauf --> die INTEL Marketing-Bombe von 1991 hält heute noch (einfach google'n 'intel inside', z.B. Angebote von MM).

Hier läuft eine Sanduhr runter denke ich - Aqara, Shelly, Dohome, Kongeek usw. sprich die CN Schiene, haben die Aktoren/Sensoren, die man gerade braucht, im Angebot zu attraktiven Preisen.
Als Techies integrieren wir das über Github 'Erzeugnisse' - klasse: nichts dagegen, ich finde den Nutzen hervorragend und spende auch an die erfindenden Ingenieure.

In Summary - Apple kann vieles - leider weiss man oft nicht, ob sie nun einen Marktrend erkennen und den bedienen, ob ob das eine Sackgasse ist.

Aber wir diskutieren hier "Node-Red" - und das ist mit Abstand die beste Meta-Ebene, die ich gesehen habe. Wenn die Kollegen sich zur Top-Level Ebene aufschwingen würden, wäre das mehr als cool.
